---
# common tasks

- name: Ensure Tempo user exist
  user:
    name: "{{ tempo_user }}"
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Deploy Tempo systemd service file
  template:
    src: tempo.service.j2
    dest: /etc/systemd/system/tempo.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Tempo service
