---
# Main tasks file for grafana_tempo role

- name: Include common install tasks
  include_tasks: install.yml

- name: OS-specific setup for Debian family
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: OS-specific setup for RedHat family
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include configuration tasks
  include_tasks: config.yml
