---
# Debian-specific setup tasks for grafana_tempo role

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install dependencies on Debian
  apt:
    name:
      - libcap2-bin
    state: present

- name: Download Tempo package for Debian
  get_url:
    url: "{{ tempo_download_url_deb }}"
    dest: "/tmp/{{ tempo_package_deb }}"
    checksum: "{{ tempo_package_checksum_deb }}"
    owner: "{{ tempo_user }}"
    mode: '0644'

- name: Install Tempo package on Debian
  apt:
    deb: "/tmp/{{ tempo_package_deb }}"

- name: "Enable tempo to ports lower than port 1024"
  community.general.capabilities:
    path: /usr/sbin/grafana-server
    capability: CAP_NET_BIND_SERVICE+ep
    state: present
  when:
    - "tempo_listening_port | int <= 1024"
    - "tempo_cap_net_bind_service"
