---
# RedHat-specific setup tasks for grafana_tempo role

- name: Install dependencies on RedHat
  yum:
    name:
      - libcap
    state: present

- name: Download Tempo package for RedHat
  get_url:
    url: "{{ tempo_download_url_rpm }}"
    dest: "/tmp/{{ tempo_package_rpm }}"
    checksum: "{{ tempo_package_checksum_rpm }}"

- name: Install Tempo package on RedHat
  yum:
    name: "/tmp/{{ tempo_package_rpm }}"
    state: present

- name: Add network capabilities to Tempo binary on RedHat
  command: setcap 'cap_net_bind_service=+ep' /usr/bin/tempo
  args:
    warn: false
